config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find_by(id: params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  # --- start ---
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path
    else
      render :new
    end
  end
  # --- end ---
  def edit
    @tweet = Tweet.find_by(id: params[:id])
  end

  def update
    @tweet = Tweet.find_by(id: params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find_by(id: params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

  private
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameHistory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<!-- rename @tweet to tweet -->
<%= form_with(model: tweet, local: true) do |form| %>
  <div>
    <h3><%= form.label :body %></h3>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit a tweet</h1>
<%= render "form", tweet: @tweet %>
<%= link_to  "Back", tweets_path %>

app/views/tweets/index.html.erb
<header class = "site-header">
  <ul class = "font">
	   <li><a class="active" href="#home">Home</a></li>
	   <li><a href="#news">Tweet</a></li>
	   <li><a href="#contact">View</a></li>
     <li><a href="#about">About</a></li>
     <li class = "last"><a>GameHistry</a></li>

  </ul>
<!--
  <div class="font">
    <h1><big><big>GameHistory</big></big></h1>
  </div>
-->
</header>
<body>
  <div class="wrapper">
        <!-- Left View -->
        <div class="LeftView">
          <iframe src="/tweets/new" frameborder="0" width="50%" height="100%"></iframe>
        </div>
  <!-- Right View -->
  <div class="RightView">
    <div class="show">
      <% @tweets.each do |tweet| %>
      <p><%= tweet.body %></p>
      <%= link_to 'Show',tweet%>
      <% end %>
    </div>
  </div>

</div>
</body>

app/views/tweets/new.html.erb
<h1>Create a new tweet</h1>

<link rel="stylesheet" href="style.css">
<!-- ADD -->
<%= render "form", tweet: @tweet %>
<!-- ADD -->

<!-- REMOVE -->
 <%= form_with(model: @tweet, local: true) do |form| %>

  <div>

  </div>
<% end %>
<!-- REMOVE -->

app/views/tweets/show.html.erb
<header class = "site-header">
  <div style="margin:0px;">
  <ul class = "font">
	   <li><a class="active" href="#home">Home</a></li>
	   <li><a href="#news">Tweet</a></li>
	   <li><a href="#contact">View</a></li>
     <li><a href="#about">About</a></li>
     <li class = "last"><a>GameHistry</a></li>

  </ul>
</div>
<!--
  <div class="font">
    <h1><big><big>GameHistory</big></big></h1>
  </div>
-->
</header>
<h1>詳細</h1>

<h3><%= @tweet.body %></h3>
<p><%= @tweet.updated_at %><p>
<%= link_to  "戻る", :back %>

<%= link_to "変更",edit_tweet_path(@tweet)%>
<%= link_to '消しますよ', @tweet, method: :delete, data:{ confirm: 'Are you sure?' } %>